version: "3"
services:
  navidrome:
    image: deluan/navidrome:0.49.3
    container_name: navidrome
    networks:
      - homenas
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_PORT: "4533"
    volumes:
      - "/opt/navidrome/data:/data"
      - "/data/music:/music:ro"

  music-downloader:
    image: bernylinville/qq_flac_music_downloader:2023-10-13
    container_name: music
    networks:
      - homenas
    ports:
      - "8899:8899"
    volumes:
      - /data/music:/workspace/music
    restart: always

networks:
  homenas:
    external: true
